name: batch
description: A Lightweight and Powerful Job Scheduling Framework written in Dart. With this framework, you can easily develop a scheduled workflow in Dart.
version: 1.3.0
homepage: https://github.com/batch-dart/batch.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.1
  console_color: ^3.0.0
  http: ^0.13.5
  args: ^2.3.2
  async_task: ^1.0.20
  intl: ^0.18.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.0
  import_sorter: ^4.6.0
  dart_code_metrics: ^5.5.1
  mock_web_server: ^5.0.0-nullsafety.1
