name: Release

on:
  push:
    tags:
      - v*

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        with:
          status: |
            Hey what's up? 🍿 New version of Batch.dart was released! 🐦🐦🐦
            Release note: https://github.com/batch-dart/batch.dart/blob/main/CHANGELOG.md

            #dart #dartlang #framework #github #pubdev #programming #100DaysOfCode

            This tweet was sent from GitHub Actions workflow at https://github.com/batch-dart/batch.dart
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
